<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>CreepyUtil.Archipelago.WorldFactory.Template</PackageId>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <AppxSymbolPackageEnabled>true</AppxSymbolPackageEnabled>
        <AppxSymbolPackageOutput>snupkg</AppxSymbolPackageOutput>
        <DebugSymbols>true</DebugSymbols>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <Version>0.1.0</Version>
        <Title>SW_CreeperKing's Archipelago World Factory Utility Template</Title>
        <Authors>SW_CreeperKing</Authors>
        <Description>A Template Utility for reading in a CSV and creating ApWorlds</Description>
        <PackageProjectUrl>https://github.com/SWCreeperKing/ApWorldFactories/tree/master/WorldBuilder</PackageProjectUrl>
        <RepositoryUrl>https://github.com/SWCreeperKing/ApWorldFactories/tree/master/WorldBuilder</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CreepyUtil.Archipelago.WorldFactory" Version="0.2.2.7" />
      <PackageReference Include="CreepyUtil.ClrCnsl" Version="0.2.0" />
      <PackageReference Include="CreepyUtil.ClrCnsl.Prompts" Version="0.2.0" />
      <PackageReference Include="CreepyUtil.Pos" Version="0.2.0" />
    </ItemGroup>

</Project>
